mockserver:
  port: 10001
  tcp-mappings-path: file:${user.home}/.tcp-mocker/tcp-mappings

spring:
  main:
    web-application-type: servlet # TODO: change to reactive
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  groovy:
    template:
      check-template-location: false
