version: "2"
services:
  maven:
    image: openjdk:8u181-jdk-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.m2:/root/.m2
      - $PWD:$PWD
    working_dir: $PWD 
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx2G"
    command: ./mvnw -e clean install
